dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.8.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.3
  png-tools:
    path: ..
  png_display:
    url: github.com/toitware/toit-png-display
    version: ^0.3.0
