dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  png_display:
    url: github.com/toitware/toit-png-display
    version: ^0.2.0
  png_reader:
    path: ..
